/**
 * Pre-built skills from the coderClaw agent directory.
 * These are available in the marketplace as built-in skills.
 */

export interface BuiltinSkill {
  name: string;
  slug: string;
  description: string;
  emoji: string;
  category: string;
  tags: string[];
  author: string;
  version: string;
  likes: number;
  downloads: number;
  image?: string;
}

export const BUILTIN_SKILLS: BuiltinSkill[] = [
  {
    name: "GitHub",
    slug: "github",
    description: "GitHub operations via gh CLI: issues, PRs, CI runs, code review, API queries.",
    emoji: "🐙",
    category: "Development",
    tags: ["git", "ci", "code-review", "issues"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 456,
    downloads: 2100,
    image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=400&h=200&fit=crop",
  },
  {
    name: "Coding Agent",
    slug: "coding-agent",
    description: "Delegate coding tasks to Codex, Claude Code, or Pi agents via background process for building features, reviewing PRs, and refactoring.",
    emoji: "🧩",
    category: "Development",
    tags: ["coding", "agents", "automation"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 389,
    downloads: 1800,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=200&fit=crop",
  },
  {
    name: "coderClaw",
    slug: "coderclaw",
    description: "Multi-agent developer system for code creation, review, testing, debugging, and architecture with memory-aware orchestration.",
    emoji: "🛠️",
    category: "Development",
    tags: ["multi-agent", "orchestration", "code-analysis"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 512,
    downloads: 3200,
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=200&fit=crop",
  },
  {
    name: "Skill Creator",
    slug: "skill-creator",
    description: "Create or update AgentSkills. Design, structure, and package skills with scripts, references, and assets.",
    emoji: "📦",
    category: "Development",
    tags: ["skills", "packaging", "authoring"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 198,
    downloads: 760,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=200&fit=crop",
  },
  {
    name: "GitHub Issues",
    slug: "gh-issues",
    description: "Fetch GitHub issues, spawn sub-agents to implement fixes and open PRs, then monitor and address PR review comments.",
    emoji: "🔧",
    category: "Development",
    tags: ["github", "issues", "automation", "prs"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 312,
    downloads: 1540,
    image: "https://images.unsplash.com/photo-1516534775068-bb6c2b8b4d44?w=400&h=200&fit=crop",
  },
  {
    name: "Slack",
    slug: "slack",
    description: "Control Slack from CoderClaw including reacting to messages and pinning/unpinning items in channels or DMs.",
    emoji: "💬",
    category: "Communication",
    tags: ["slack", "messaging", "chat"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 267,
    downloads: 1100,
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=400&h=200&fit=crop",
  },
  {
    name: "Discord",
    slug: "discord",
    description: "Discord operations via the message tool for sending and managing messages in Discord channels.",
    emoji: "🎮",
    category: "Communication",
    tags: ["discord", "messaging", "bots"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 234,
    downloads: 980,
    image: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=400&h=200&fit=crop",
  },
  {
    name: "Himalaya (Email)",
    slug: "himalaya",
    description: "CLI to manage emails via IMAP/SMTP. List, read, write, reply, forward, search, and organize emails from the terminal.",
    emoji: "📧",
    category: "Communication",
    tags: ["email", "imap", "smtp"],
    author: "pimalaya",
    version: "1.0.0",
    likes: 178,
    downloads: 720,
    image: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&h=200&fit=crop",
  },
  {
    name: "Notion",
    slug: "notion",
    description: "Notion API for creating and managing pages, databases, and blocks.",
    emoji: "📝",
    category: "Productivity",
    tags: ["notion", "notes", "databases"],
    author: "Notion",
    version: "1.0.0",
    likes: 289,
    downloads: 1300,
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=200&fit=crop",
  },
  {
    name: "Obsidian",
    slug: "obsidian",
    description: "Work with Obsidian vaults (plain Markdown notes) and automate via obsidian-cli.",
    emoji: "💎",
    category: "Productivity",
    tags: ["obsidian", "notes", "markdown"],
    author: "Obsidian",
    version: "1.0.0",
    likes: 245,
    downloads: 1050,
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=400&h=200&fit=crop",
  },
  {
    name: "Bear Notes",
    slug: "bear-notes",
    description: "Create, search, and manage Bear notes via grizzly CLI.",
    emoji: "🐻",
    category: "Productivity",
    tags: ["bear", "notes", "macos"],
    author: "tylerwince",
    version: "1.0.0",
    likes: 134,
    downloads: 520,
    image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400&h=200&fit=crop",
  },
  {
    name: "Apple Notes",
    slug: "apple-notes",
    description: "iMessage/SMS CLI for Apple Notes integration on macOS.",
    emoji: "📨",
    category: "Productivity",
    tags: ["apple", "notes", "macos"],
    author: "antoniorodr",
    version: "1.0.0",
    likes: 112,
    downloads: 430,
  },
  {
    name: "Things 3",
    slug: "things-mac",
    description: "Manage Things 3 via the things CLI on macOS — add/update projects and todos, list inbox/today/upcoming, search tasks.",
    emoji: "✅",
    category: "Productivity",
    tags: ["tasks", "todo", "macos"],
    author: "ossianhempel",
    version: "1.0.0",
    likes: 167,
    downloads: 680,
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=200&fit=crop",
  },
  {
    name: "Apple Reminders",
    slug: "apple-reminders",
    description: "Manage Apple Reminders on macOS for task tracking and reminder creation.",
    emoji: "⏰",
    category: "Productivity",
    tags: ["reminders", "tasks", "macos"],
    author: "steipete",
    version: "1.0.0",
    likes: 98,
    downloads: 390,
  },
  {
    name: "Trello",
    slug: "trello",
    description: "Manage Trello boards, lists, and cards via the Trello REST API.",
    emoji: "📋",
    category: "Productivity",
    tags: ["trello", "boards", "project-management"],
    author: "Atlassian",
    version: "1.0.0",
    likes: 201,
    downloads: 870,
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=200&fit=crop",
  },
  {
    name: "Google Workspace (gog)",
    slug: "gog",
    description: "Google Workspace CLI for Gmail, Calendar, Drive, Contacts, Sheets, and Docs.",
    emoji: "🎮",
    category: "Productivity",
    tags: ["google", "gmail", "calendar", "drive"],
    author: "gogcli",
    version: "1.0.0",
    likes: 345,
    downloads: 1650,
    image: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=400&h=200&fit=crop",
  },
  {
    name: "Gemini",
    slug: "gemini",
    description: "Gemini CLI for one-shot Q&A, summaries, and generation.",
    emoji: "♊️",
    category: "AI & ML",
    tags: ["gemini", "ai", "generation"],
    author: "Google",
    version: "1.0.0",
    likes: 278,
    downloads: 1200,
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=200&fit=crop",
  },
  {
    name: "OpenAI Image Gen",
    slug: "openai-image-gen",
    description: "Batch-generate images via OpenAI Images API with random prompt sampler and gallery.",
    emoji: "🖼️",
    category: "AI & ML",
    tags: ["openai", "images", "generation"],
    author: "OpenAI",
    version: "1.0.0",
    likes: 234,
    downloads: 950,
    image: "https://images.unsplash.com/photo-1547954575-855750c57bd3?w=400&h=200&fit=crop",
  },
  {
    name: "Nano Banana Pro",
    slug: "nano-banana-pro",
    description: "Generate or edit images via Gemini 3 Pro Image (Nano Banana Pro).",
    emoji: "🍌",
    category: "AI & ML",
    tags: ["gemini", "images", "editing"],
    author: "Google",
    version: "1.0.0",
    likes: 156,
    downloads: 620,
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=200&fit=crop",
  },
  {
    name: "OpenAI Whisper",
    slug: "openai-whisper",
    description: "Local speech-to-text with the Whisper CLI (no API key required).",
    emoji: "🎙️",
    category: "AI & ML",
    tags: ["whisper", "speech-to-text", "transcription"],
    author: "OpenAI",
    version: "1.0.0",
    likes: 189,
    downloads: 830,
    image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400&h=200&fit=crop",
  },
  {
    name: "Whisper API",
    slug: "openai-whisper-api",
    description: "Transcribe audio via OpenAI Audio Transcriptions API (cloud Whisper).",
    emoji: "☁️",
    category: "AI & ML",
    tags: ["whisper", "transcription", "api"],
    author: "OpenAI",
    version: "1.0.0",
    likes: 145,
    downloads: 590,
  },
  {
    name: "Sherpa ONNX TTS",
    slug: "sherpa-onnx-tts",
    description: "Local text-to-speech via sherpa-onnx (offline, no cloud).",
    emoji: "🗣️",
    category: "AI & ML",
    tags: ["tts", "speech", "offline"],
    author: "k2-fsa",
    version: "1.0.0",
    likes: 123,
    downloads: 480,
  },
  {
    name: "Sag (ElevenLabs TTS)",
    slug: "sag",
    description: "ElevenLabs text-to-speech with mac-style say UX.",
    emoji: "🗣️",
    category: "AI & ML",
    tags: ["tts", "elevenlabs", "speech"],
    author: "sag",
    version: "1.0.0",
    likes: 167,
    downloads: 710,
  },
  {
    name: "Summarize",
    slug: "summarize",
    description: "Summarize or extract text/transcripts from URLs, podcasts, and local files.",
    emoji: "🧾",
    category: "AI & ML",
    tags: ["summarization", "transcripts", "extraction"],
    author: "Summarize",
    version: "1.0.0",
    likes: 298,
    downloads: 1400,
    image: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=400&h=200&fit=crop",
  },
  {
    name: "Spotify Player",
    slug: "spotify-player",
    description: "Terminal Spotify playback and search via spogo or spotify_player.",
    emoji: "🎵",
    category: "Media",
    tags: ["spotify", "music", "playback"],
    author: "Spotify",
    version: "1.0.0",
    likes: 345,
    downloads: 1500,
    image: "https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=400&h=200&fit=crop",
  },
  {
    name: "Sonos CLI",
    slug: "sonoscli",
    description: "Control Sonos speakers: discover, status, play, volume, and group.",
    emoji: "🔊",
    category: "Media",
    tags: ["sonos", "speakers", "audio"],
    author: "SonosCLI",
    version: "1.0.0",
    likes: 134,
    downloads: 540,
  },
  {
    name: "BluOS CLI",
    slug: "blucli",
    description: "BluOS CLI for discovery, playback, grouping, and volume control.",
    emoji: "🫐",
    category: "Media",
    tags: ["bluos", "speakers", "audio"],
    author: "BluCLI",
    version: "1.0.0",
    likes: 87,
    downloads: 340,
  },
  {
    name: "Song See",
    slug: "songsee",
    description: "Generate spectrograms and feature-panel visualizations from audio.",
    emoji: "🌊",
    category: "Media",
    tags: ["audio", "spectrograms", "visualization"],
    author: "steipete",
    version: "1.0.0",
    likes: 98,
    downloads: 380,
  },
  {
    name: "Video Frames",
    slug: "video-frames",
    description: "Extract frames or short clips from videos using ffmpeg.",
    emoji: "🎞️",
    category: "Media",
    tags: ["video", "ffmpeg", "extraction"],
    author: "FFmpeg",
    version: "1.0.0",
    likes: 156,
    downloads: 620,
    image: "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=400&h=200&fit=crop",
  },
  {
    name: "GIF Grep",
    slug: "gifgrep",
    description: "Search GIF providers, download results, and extract stills/sheets.",
    emoji: "🧲",
    category: "Media",
    tags: ["gifs", "search", "images"],
    author: "GifGrep",
    version: "1.0.0",
    likes: 178,
    downloads: 730,
  },
  {
    name: "CamSnap",
    slug: "camsnap",
    description: "Capture frames or clips from RTSP/ONVIF cameras.",
    emoji: "📸",
    category: "IoT & Hardware",
    tags: ["cameras", "rtsp", "capture"],
    author: "CamSnap",
    version: "1.0.0",
    likes: 112,
    downloads: 450,
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=400&h=200&fit=crop",
  },
  {
    name: "Peekaboo",
    slug: "peekaboo",
    description: "Capture and automate macOS UI with the Peekaboo CLI.",
    emoji: "👀",
    category: "IoT & Hardware",
    tags: ["macos", "ui", "automation"],
    author: "Peekaboo",
    version: "1.0.0",
    likes: 134,
    downloads: 520,
  },
  {
    name: "OpenHue",
    slug: "openhue",
    description: "Control Philips Hue lights and scenes via the OpenHue CLI.",
    emoji: "💡",
    category: "IoT & Hardware",
    tags: ["hue", "lights", "smart-home"],
    author: "OpenHue",
    version: "1.0.0",
    likes: 189,
    downloads: 780,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=200&fit=crop",
  },
  {
    name: "Eight Sleep",
    slug: "eightctl",
    description: "Control Eight Sleep pods: status, temperature, alarms, schedules.",
    emoji: "🎛️",
    category: "IoT & Hardware",
    tags: ["sleep", "smart-home", "temperature"],
    author: "Eight Sleep",
    version: "1.0.0",
    likes: 98,
    downloads: 390,
  },
  {
    name: "Weather",
    slug: "weather",
    description: "Get current weather and forecasts via wttr.in or Open-Meteo. No API key needed.",
    emoji: "🌤️",
    category: "Utilities",
    tags: ["weather", "forecasts"],
    author: "wttr.in",
    version: "1.0.0",
    likes: 234,
    downloads: 1200,
    image: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=400&h=200&fit=crop",
  },
  {
    name: "Google Places",
    slug: "goplaces",
    description: "Query Google Places API for text search, place details, resolve, and reviews.",
    emoji: "📍",
    category: "Utilities",
    tags: ["google", "places", "maps"],
    author: "steipete",
    version: "1.0.0",
    likes: 156,
    downloads: 640,
  },
  {
    name: "Nano PDF",
    slug: "nano-pdf",
    description: "Edit PDFs with natural-language instructions using the nano-pdf CLI.",
    emoji: "📄",
    category: "Utilities",
    tags: ["pdf", "editing", "documents"],
    author: "nano-pdf",
    version: "1.0.0",
    likes: 167,
    downloads: 690,
  },
  {
    name: "MCP Porter",
    slug: "mcporter",
    description: "List, configure, auth, and call MCP servers/tools directly including ad-hoc servers and CLI generation.",
    emoji: "📦",
    category: "Utilities",
    tags: ["mcp", "servers", "tools"],
    author: "MCPorter",
    version: "1.0.0",
    likes: 201,
    downloads: 850,
  },
  {
    name: "ClawHub",
    slug: "clawhub",
    description: "Search, install, update, and publish agent skills from clawhub.com.",
    emoji: "🦞",
    category: "Utilities",
    tags: ["clawhub", "skills", "registry"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 278,
    downloads: 1150,
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&h=200&fit=crop",
  },
  {
    name: "Oracle",
    slug: "oracle",
    description: "Prompt + file bundling, engines, sessions, and file attachment patterns via the oracle CLI.",
    emoji: "🧿",
    category: "Utilities",
    tags: ["oracle", "prompts", "bundling"],
    author: "AskOracle",
    version: "1.0.0",
    likes: 112,
    downloads: 450,
  },
  {
    name: "tmux",
    slug: "tmux",
    description: "Remote-control tmux sessions for interactive CLIs by sending keystrokes and scraping pane output.",
    emoji: "🧵",
    category: "Utilities",
    tags: ["tmux", "terminal", "sessions"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 145,
    downloads: 580,
  },
  {
    name: "Voice Call",
    slug: "voice-call",
    description: "Start voice calls via the CoderClaw voice-call plugin.",
    emoji: "📞",
    category: "Communication",
    tags: ["voice", "calls", "telephony"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 189,
    downloads: 780,
  },
  {
    name: "WhatsApp (wacli)",
    slug: "wacli",
    description: "Send WhatsApp messages or search/sync WhatsApp history via the wacli CLI.",
    emoji: "📱",
    category: "Communication",
    tags: ["whatsapp", "messaging"],
    author: "WaCLI",
    version: "1.0.0",
    likes: 234,
    downloads: 980,
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=200&fit=crop",
  },
  {
    name: "BlueBubbles (iMessage)",
    slug: "bluebubbles",
    description: "Send and manage iMessages via BlueBubbles — recommended iMessage integration.",
    emoji: "🫧",
    category: "Communication",
    tags: ["imessage", "messaging", "macos"],
    author: "BlueBubbles",
    version: "1.0.0",
    likes: 167,
    downloads: 690,
  },
  {
    name: "iMessage (imsg)",
    slug: "imsg",
    description: "iMessage/SMS CLI for listing chats, history, and sending messages via Messages.app.",
    emoji: "📨",
    category: "Communication",
    tags: ["imessage", "sms", "macos"],
    author: "iMsg",
    version: "1.0.0",
    likes: 145,
    downloads: 580,
  },
  {
    name: "Blog Watcher",
    slug: "blogwatcher",
    description: "Monitor blogs and RSS/Atom feeds for updates using the blogwatcher CLI.",
    emoji: "📰",
    category: "Utilities",
    tags: ["rss", "blogs", "monitoring"],
    author: "Hyaxia",
    version: "1.0.0",
    likes: 112,
    downloads: 430,
  },
  {
    name: "Food Order",
    slug: "food-order",
    description: "Reorder Foodora orders and track ETA/status with ordercli. Never confirms without explicit user approval.",
    emoji: "🥡",
    category: "Utilities",
    tags: ["food", "delivery", "ordering"],
    author: "OrderCLI",
    version: "1.0.0",
    likes: 98,
    downloads: 370,
  },
  {
    name: "Session Logs",
    slug: "session-logs",
    description: "Search and analyze your own session logs (older/parent conversations) using jq.",
    emoji: "📜",
    category: "Utilities",
    tags: ["logs", "sessions", "analysis"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 134,
    downloads: 520,
  },
  {
    name: "Model Usage",
    slug: "model-usage",
    description: "Summarize per-model usage and costs from CodexBar for Codex or Claude.",
    emoji: "📊",
    category: "Utilities",
    tags: ["usage", "costs", "analytics"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 156,
    downloads: 630,
  },
  {
    name: "Health Check",
    slug: "healthcheck",
    description: "Host security hardening and risk-tolerance configuration for CoderClaw deployments.",
    emoji: "🛡️",
    category: "Security",
    tags: ["security", "hardening", "audit"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 234,
    downloads: 1100,
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=200&fit=crop",
  },
  {
    name: "1Password",
    slug: "1password",
    description: "1Password CLI integration for secure credential access and management.",
    emoji: "🔐",
    category: "Security",
    tags: ["passwords", "secrets", "1password"],
    author: "1Password",
    version: "1.0.0",
    likes: 312,
    downloads: 1450,
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=200&fit=crop",
  },
  {
    name: "Canvas",
    slug: "canvas",
    description: "Canvas skill for visual and diagrammatic content creation.",
    emoji: "🎨",
    category: "Media",
    tags: ["canvas", "visual", "diagrams"],
    author: "coderClaw",
    version: "1.0.0",
    likes: 189,
    downloads: 780,
  },
];
